version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://benchmark:benchmark123@mysql-symfony:3306/benchmark"
    networks:
      - symfony-network

  nginx:
    image: nginx:stable
    ports:
      - "8123:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - symfony-network

  mysql-symfony:
    image: mysql:8.0
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=benchmark
      - MYSQL_USER=benchmark
      - MYSQL_PASSWORD=benchmark123
    volumes:
      - mysql-symfony-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  mysql-symfony-data:
